#!/bin/sh
apt update --fix-missing
apt-get install -y build-essential
cd /usr/local
wget "https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.38-9760-rtm/softether-vpnserver-v4.38-9760-rtm-2021.08.17-linux-x64-64bit.tar.gz" -O archive.tar.gz
tar -zxvf archive.tar.gz
cd vpnserver/
make
chmod 600 *
chmod 700 vpnserver
chmod 700 vpncmd
./vpncmd
echo "---- Вбиваете 3 + Enter + check в результате должно вывести – All checks passed."
./vpnserver start
./vpncmd 
echo "---- 1 + Enter + Enter + serverpasswordset - устанавливаете пароль и exit"
./vpnserver stop
cat >>/etc/init.d/vpnserver <<EOF
#!/bin/sh
### BEGIN INIT INFO
# Provides:          vpnserver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable Softether by daemon.
### END INIT INFO
DAEMON=/usr/local/vpnserver/vpnserver
LOCK=/var/lock/subsys/vpnserver
test -x $DAEMON || exit 0
case "$1" in
start)
$DAEMON start
touch $LOCK
;;
stop)
$DAEMON stop
rm $LOCK
;;
restart)
$DAEMON stop
sleep 3
$DAEMON start
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
esac
exit 0
EOF
chmod 755 /etc/init.d/vpnserver
update-rc.d vpnserver defaults
systemctl start vpnserver
systemctl status vpnserver
